# Generated by Django 5.2.5 on 2025-08-18 09:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('house', 'House'), ('hotel', 'Hotel'), ('event', 'Event')], max_length=10)),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('wilaya', models.CharField(max_length=50)),
                ('municipality', models.CharField(max_length=50)),
                ('postal_code', models.CharField(blank=True, max_length=10, null=True)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('hidden', 'Hidden'), ('deleted', 'Deleted')], default='draft', max_length=20)),
                ('capacity', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HouseDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_type', models.CharField(max_length=20)),
                ('rooms', models.IntegerField()),
                ('bathrooms', models.IntegerField()),
                ('furnished', models.BooleanField(default=False)),
                ('amenities', models.JSONField(default=dict)),
                ('rules', models.JSONField(default=dict)),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=12)),
                ('min_stay', models.IntegerField(default=1)),
                ('contract_required', models.CharField(choices=[('none', 'None'), ('mandatory', 'Mandatory'), ('optional', 'Optional')], default='none', max_length=20)),
                ('listing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='house_detail', to='app.listing')),
            ],
        ),
        migrations.CreateModel(
            name='HotelDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_type', models.CharField(max_length=20)),
                ('stars', models.IntegerField(default=0)),
                ('services', models.JSONField(default=dict)),
                ('contact_phone', models.CharField(max_length=20)),
                ('contact_email', models.EmailField(max_length=254)),
                ('listing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_detail', to='app.listing')),
            ],
        ),
        migrations.CreateModel(
            name='EventDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=50)),
                ('date_start', models.DateField()),
                ('date_end', models.DateField(blank=True, null=True)),
                ('family_friendly', models.BooleanField(default=False)),
                ('gender_preference', models.CharField(choices=[('mixed', 'Mixed'), ('male', 'Male Only'), ('female', 'Female Only')], default='mixed', max_length=10)),
                ('contact_info', models.JSONField(default=dict)),
                ('listing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='event_detail', to='app.listing')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('nights', models.IntegerField()),
                ('price_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='DZD', max_length=10)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('cancelled', 'Cancelled')], default='requested', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings_made', to=settings.AUTH_USER_MODEL)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings_received', to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='app.listing')),
            ],
        ),
        migrations.CreateModel(
            name='ListingMedia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], max_length=10)),
                ('object_key', models.CharField(max_length=255)),
                ('is_primary', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='app.listing')),
            ],
        ),
    ]
