# Generated by Django 5.2.5 on 2025-08-25 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_user_username_alter_listing_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='host',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='nights',
        ),
        migrations.AddField(
            model_name='booking',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='decision_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='hoteldetail',
            name='price_per_night',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('requested', 'Requested'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('cancelled_host', 'Cancelled by Host'), ('cancelled_guest', 'Cancelled by Guest')], default='requested', max_length=20),
        ),
        migrations.AlterField(
            model_name='housedetail',
            name='price_per_night',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
