# Generated by Django 5.2.5 on 2025-08-28 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_booking_host_remove_booking_nights_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
