# Generated by Django 5.2.5 on 2025-09-08 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_eventtickettype_eventticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='check_in_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='check_out_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('requested', 'Requested'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('cancelled_host', 'Cancelled by Host'), ('cancelled_guest', 'Cancelled by Guest'), ('cancelled_request', 'Cancellation Requested'), ('checked_in', 'Checked In'), ('checked_out', 'Checked Out'), ('no_show', 'No Show')], default='requested', max_length=20),
        ),
    ]
