services:
  minio:
    ports:
      - "9901:9000"    # MinIO API
      - "9902:9001"    # MinIO Console

  redis:
    ports:
      - "9903:6379" # Redis

  pgadmin:
    ports:
      - "9904:80" # pgAdmin
  
  db:
    ports:
      - "9905:5432" # Postgres