services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - static_volume:/app/static
    command: gunicorn kerya.wsgi:application --bind 0.0.0.0:8000 --workers ${WEB_CONCURRENCY}
    restart: always
    depends_on:
      - db
      - redis
      - minio

  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - static_volume:/app/static:ro
    depends_on:
      - web
    restart: always

volumes:
  static_volume:
